<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation Starter Template</title>
    <!-- Compressed CSS -->
    <link
            rel="stylesheet"
            href="/css/foundation.min.css"
    />
    <link rel="stylesheet" href="css/styles.css" />
</head>
<body>
<!-- Start Top Bar -->
<div class="top-bar">
    <div class="top-bar-left">

        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text"><a href="<?=$baseUrl?>">Multi level categories</a></li>
            <?= $categories?>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Search" /></li>
            <li><button type="button" class="button">Search</button></li>
        </ul>
    </div>
</div>
<!-- End Top Bar -->
<br />
<br />